apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aks-jmeter.jmeter.controller-config-name" . }}
  labels:
    {{- include "aks-jmeter.labels" . | nindent 4 }}
data:
  load_test: |
    #!/bin/bash
    #Script created to invoke jmeter test script with the worker POD IP addresses
    #Script should be run like: ./load_test "path to the test script in jmx format"

    /jmeter/apache-jmeter-*/bin/jmeter -n -Gpassword=$KRATER_ACR_PASSWORD -Gusername=$KRATER_ACR_USERNAME -Gloginserver=$KRATER_ACR_LOGINSERVER -t $1 -Dserver.rmi.ssl.disable=true -R `getent ahostsv4 jmeter-worker | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`