apiVersion: v1
kind: Service
metadata:
  name: {{ include "aks-jmeter.jmeter.worker-name" . }}
  labels:
    {{- include "aks-jmeter.jmeter.worker-modeLabels" . | nindent 4 }}
    {{- include "aks-jmeter.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.jmeter.worker.ports.pod.server }}
      name: server
      targetPort: {{ .Values.jmeter.worker.ports.pod.server }}
    - port: {{ .Values.jmeter.worker.ports.pod.local }}
      name: local
      targetPort: {{ .Values.jmeter.worker.ports.pod.local }}
  selector:
    {{- include "aks-jmeter.jmeter.worker-modeLabels" . | nindent 4 }}
