apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aks-jmeter.registry-secret-name" . }}
  labels:
    {{- include "aks-jmeter.labels" . | nindent 4 }}
type: Opaque
stringData:
  loginserver: {{ .Values.loginserver }}
  username: {{ .Values.username }}
  password: {{ .Values.password }}
